### PR TITLE
features comparisons updates

### PR DESCRIPTION
**Pull request by romain-dartigues**
To address some remarks:
- #90: ag uses threads
- git grep can skip it's ignore rules
- gnu grep can flush
- #88: rg can search compressed files

Open for discussion if you need exact versions of each programs.

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for this.  Are you done with commits to this now?

**Comment by romain-dartigues** [comment]
For now (^_^)!
I hope to make more useful contributions a next time...

**Comment by petdance** [comment]
I haven't merged this PR yet.  I'd still like to use it.

**Comment by petdance** [comment]
I dug up your changes and applied manaully.  Thanks.  e6a57cc

**Pull request closed without merging**
